version: "3.1"
services:
    redis:
      image: redis:6
      container_name: ali_home-redis
      environment:
        - TZ=Asia/HO_CHI_MINH
      ports:
        - "6396:6379"

    postgresql:
      image: postgres:12.2-alpine
      container_name: ali_home-postgresql
      working_dir: /application
      volumes:
        - .:/application

      environment:
        - POSTGRES_DB=ali_home
        - POSTGRES_USER=ali_home
        - POSTGRES_PASSWORD=20187a63f0901ea878fc
        - TZ=Asia/HO_CHI_MINH
        - PGTZ=Asia/HO_CHI_MINH
      ports:
        - "3316:5432"
        
    php:
      build:
        context: ./
        dockerfile: php.Dockerfile
      container_name: ali_home-php
      user: ${UID}:${GID}
      links:
        - postgresql:postgresql
        - redis:redis
      ports:
        - "9016:9000"
      volumes:
        - .:/application
        - ./:/var/www/html
        - ./docker/php/php.ini:/usr/local/etc/php/php.ini

    webserver:
      build:
        context: ./
        dockerfile: nginx.Dockerfile
      container_name: ali_home-webserver
      working_dir: /application
      links:
        - php:fpm
      environment:
        - FPM_HOST=fpm
        - FPM_PORT=9000
      volumes:
        - .:/application
        - ./:/var/www/html
        - ./storage/logs/nginx/:/var/log/nginx
        - ./docker/nginx_conf:/etc/nginx/conf.d/
      ports:
        - "8016:80"
